### ISSUE TITLE
After install finrock locally, when I run your code, still can not find module name

### ISSUE THREAD

**Issue by Rockywei1** [pythonlessons/FinRock#10]
Hello, I put requirements.txt / README.MD / __int__.py into finrock folder

And run pip install .

It works, I'm pretty sure finrock and wheels all successfully installed

But when I run the code, the error still says ModuleNotFoundError: No module named 'finrock'

I'm looking forward you publish your package so I think it will fix this problem

Cheers

**Comment by pythonlessons** [comment]
Thanks, I'll check this. I'll add this package to pypi

**Comment by danielm1515** [comment]
This still missing :\
