### ISSUE TITLE
Possible division by 0 in the hold_reward function

### ISSUE THREAD

**Issue by vick2592** [pythonlessons/FinRock#4]
This is the quoted response when I had Copilot explain to me the hold_reward function 

"The hold_reward is a part of the reward calculation in the SimpleReward class. It represents the reward for the portion of the asset that was held (not bought or sold) between the last state and the next state.
The hold_reward is calculated as the percentage change in the closing price of the asset times the allocation percentage. The allocation percentage represents the portion of the portfolio that is allocated to the asset.
Here's how it's calculated in each case:
1.	Buy: If the allocation percentage increases from the last state to the next state, this means that some of the asset was bought. The hold_reward is calculated based on the last state's allocation percentage, because this is the portion of the asset that was held.
2.	Sell: If the allocation percentage decreases, this means that some of the asset was sold. The hold_reward is calculated based on the next state's allocation percentage, because this is the portion of the asset that was held after selling.
3.	Hold: If the allocation percentage doesn't change, this means that all of the asset was held. The reward is calculated based on the last state's allocation percentage, but with a negative sign if the allocation percentage is zero. This is because if no asset is held, the reward should be zero, but the formula (next_state.close - last_state.close) / last_state.close * ratio would result in a division by zero error.
In all cases, the hold_reward is added to the reward variable, which is then returned by the function. This means that the total reward for each action (buy, sell, or hold) is a combination of the reward for the action itself and the reward for the portion of the asset that was held."

As you can see in number 3 is where it brings up the issue. To my understanding, for this edge case to occur, there would have to be some kind of positive outcome from a next_state.close - last_state.close while holding. Otherwise if the last_state.close was a hold your next state.close also is a hold so it would mean hold_reward would be 0/0 = 0. I might be wrong, though. Let me know what you think.

**Comment by pythonlessons** [comment]
Hey, thanks for this response. Here is the reward function:

```python
class SimpleReward(Reward):
    def __init__(self) -> None:
        super().__init__()

    def __call__(self, observations: Observations) -> float:
        assert isinstance(observations, Observations) == True, "observations must be an instance of Observations"

        last_state, next_state = observations[-2:]

        # buy
        if next_state.allocation_percentage > last_state.allocation_percentage:
            # check whether it was good or bad to buy
            order_size = next_state.allocation_percentage - last_state.allocation_percentage
            reward = (next_state.close - last_state.close) / last_state.close * order_size
            hold_reward = (next_state.close - last_state.close) / last_state.close * last_state.allocation_percentage
            reward += hold_reward

        # sell
        elif next_state.allocation_percentage < last_state.allocation_percentage:
            # check whether it was good or bad to sell
            order_size = last_state.allocation_percentage - next_state.allocation_percentage
            reward = -1 * (next_state.close - last_state.close) / last_state.close * order_size
            hold_reward = (next_state.close - last_state.close) / last_state.close * next_state.allocation_percentage
            reward += hold_reward

        # hold
        else:
            # check whether it was good or bad to hold
            ratio = -1 if not last_state.allocation_percentage else last_state.allocation_percentage
            reward = (next_state.close - last_state.close) / last_state.close * ratio
            
        return reward
```        

but I can't find a situation when there might be division by zero
```(next_state.close - last_state.close) / last_state.close * ratio```
because `last_state.close` and `next_state.close` will never become zero

and that's the reason why I define ratio as -1 when allocation_percentage is 0, to find out whether it was good or bad to wait for next step without assets

That's my opinion

**Comment by vick2592** [comment]
I see, yes that makes sense, cause according to Chat GPT the time will only be 0 when last_state.close and last_state.allocation_percentage is 0. "In the provided code, the potential division by zero occurs in the following line:

python

ratio = -1 if not last_state.allocation_percentage else last_state.allocation_percentage

Here, the code is attempting to calculate the reward for the "hold" scenario. It checks if last_state.allocation_percentage is zero or not before assigning it to ratio. If last_state.allocation_percentage is zero, it assigns -1 to ratio. This is done to handle the case when last_state.allocation_percentage is zero to avoid division by zero later in the code.

However, if last_state.allocation_percentage is indeed zero, the code will still proceed to the calculation:

python

reward = (next_state.close - last_state.close) / last_state.close * ratio

In this calculation, there is a division by last_state.close, and if last_state.close is also zero, it will result in a division by zero error.

To prevent this issue, you should add a check for last_state.close before performing the division. For example:

python

if last_state.close != 0:
    reward = (next_state.close - last_state.close) / last_state.close * ratio
else:
    # Handle the case when last_state.close is zero (avoid division by zero)
    reward = 0  # or any appropriate value

This modification ensures that the division is only performed when last_state.close is not zero, preventing a division by zero error." Please check its solution to see if it is slightly better. Also, according to your code, why does -1 determine if it was good or bad to wait for the next step without assets?

**Comment by pythonlessons** [comment]
if we got last_state.close == 0, we would need to raise an error instead of setting the reward to 0 because this scenario is impossible, and it would mean that something is wrong in the code.

Now I'll give you an example with -1.

for example, last_state.allocation_percentage = 0, next_state.close = 10, last_state.close = 9
```
ratio = -1
reward = (10 - 9) / 9 * -1 = -0.111
```

for example, last_state.allocation_percentage = 0, next_state.close = 9, last_state.close = 10
```
ratio = -1
reward = (9 - 10) / 10 * -1 = 0.1
```

as you can see, in the first case, our reward is negative because it was not a good idea to hold. And in the second case, we received a positive reward because it was good to hold our asses.

**Comment by vick2592** [comment]
I see, thank you for explaining this. Makes sense. =)
